"""Discovery step: mine ATS slugs from the community-repo application URLs and
write them to config/harvested.yml so the poller can hit those companies directly
(low latency, mostly startups). Run periodically: python -m src.harvest

Kept separate from the per-run poll so polling stays fast and the harvested list
stays reviewable/diffable in git.
"""
from __future__ import annotations

import os
import re

import yaml

from . import sources

CONFIG_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "config")
HARVEST_PATH = os.path.join(CONFIG_DIR, "harvested.yml")

# Directly-pollable ATS hosts → slug. Workday is excluded (needs tenant+site, not
# derivable from the host alone).
PATTERNS = {
    "greenhouse": re.compile(r"(?:boards|job-boards)\.greenhouse\.io/(?:embed/job_app\?for=)?([a-z0-9_-]+)", re.I),
    "lever": re.compile(r"jobs\.lever\.co/([a-z0-9_-]+)", re.I),
    "ashby": re.compile(r"jobs\.ashbyhq\.com/([a-z0-9_-]+)", re.I),
    "smartrecruiters": re.compile(r"jobs\.smartrecruiters\.com/([a-z0-9_-]+)", re.I),
    "bamboohr": re.compile(r"([a-z0-9-]+)\.bamboohr\.com", re.I),
}
# Slugs that are ATS plumbing, not companies.
BLOCK = {"embed", "job_app", "job-boards", "boards"}


def harvest(companies: dict) -> dict:
    found = {k: set() for k in PATTERNS}
    for repo in companies.get("repos", []) or []:
        for listing in sources.fetch_repo(repo):
            url = listing.get("url", "")
            for prov, rx in PATTERNS.items():
                m = rx.search(url)
                if m:
                    slug = m.group(1).lower()
                    if slug not in BLOCK:
                        found[prov].add(slug)
    return {k: sorted(v) for k, v in found.items()}


def main() -> None:
    with open(os.path.join(CONFIG_DIR, "companies.yml")) as f:
        companies = yaml.safe_load(f)

    harvested = harvest(companies)
    # Don't restate slugs already curated by hand.
    for prov in harvested:
        curated = set(companies.get(prov, []) or [])
        harvested[prov] = [s for s in harvested[prov] if s not in curated]

    with open(HARVEST_PATH, "w") as f:
        f.write("# Auto-generated by `python -m src.harvest` — ATS slugs mined from repo URLs.\n")
        f.write("# Mostly startups. Merged into the poll on top of companies.yml.\n")
        yaml.safe_dump(harvested, f, default_flow_style=False, sort_keys=True)

    total = sum(len(v) for v in harvested.values())
    print(f"harvested {total} new slugs -> config/harvested.yml")
    for prov, slugs in harvested.items():
        print(f"  {prov}: {len(slugs)}")


if __name__ == "__main__":
    main()
